/// Piecewise cubic CDF approximation — drop-in replacement for
/// deepbook_predict::math::normal_cdf (Abramowitz & Stegun 26.2.17).
///
/// Forked from: https://github.com/MystenLabs/deepbookv3/blob/main/packages/predict/sources/helper/math.move
///
/// The original A&S approach computes exp(-x^2/2) via a 12-iteration Taylor
/// series, which accounts for 56% of bytecode instructions (380 of 674).
/// This module replaces the entire CDF with 8 precomputed cubic polynomials,
/// one per segment of [0, 4]. No exp(), no Taylor series, no loops.
///
/// Bytecode instructions per call:  674 (A&S) -> 130 (piecewise) = 5.2x reduction
/// Gas at 100 calls (vault rebalance): 254,000 -> 13,000 = 19.5x reduction
///   (amplified by Sui's tiered instruction pricing — A&S hits 10x tier, piecewise stays in 1x)
///
/// Max error: 0.17 basis points (1.75e-5). Monotonicity analytically verified.
/// See ANALYSIS.md for full derivation and validation.
#[allow(unused_const)]
module predict_math_opt::piecewise_cdf;

use predict_math_opt::math_utils;

const FLOAT_SCALING: u64 = 1_000_000_000;

// Half-unit boundary in FLOAT_SCALING
const HALF: u64 = 500_000_000;

// === Piecewise Cubic Coefficients ===
// P(x) = A + B*x + C*x² + D*x³ for x in [seg*0.5, (seg+1)*0.5)
// Generated by scripts/generate_coefficients.py
// Max overall error: 1.75e-5 (0.17 bp)

// Segment 0: [0.0, 0.5) — max error 0.10 bp
const SEG0_A: u64 = 500_000_001;
const SEG0_B: u64 = 399_206_645;
const SEG0_C: u64 = 2_650_878;
const SEG0_C_NEG: bool = true;
const SEG0_D: u64 = 59_825_087;
const SEG0_D_NEG: bool = true;

// Segment 1: [0.5, 1.0) — max error 0.17 bp
const SEG1_A: u64 = 494_143_282;
const SEG1_B: u64 = 431_092_503;
const SEG1_C: u64 = 61_925_478;
const SEG1_C_NEG: bool = true;
const SEG1_D: u64 = 21_965_566;
const SEG1_D_NEG: bool = true;

// Segment 2: [1.0, 1.5) — max error 0.11 bp
const SEG2_A: u64 = 456_503_869;
const SEG2_B: u64 = 544_003_886;
const SEG2_C: u64 = 175_873_998;
const SEG2_C_NEG: bool = true;
const SEG2_D: u64 = 16_710_983;
const SEG2_D_NEG: bool = false;

// Segment 3: [1.5, 2.0) — max error 0.008 bp
const SEG3_A: u64 = 420_344_025;
const SEG3_B: u64 = 620_314_028;
const SEG3_C: u64 = 229_648_030;
const SEG3_C_NEG: bool = true;
const SEG3_D: u64 = 29_358_747;
const SEG3_D_NEG: bool = false;

// Segment 4: [2.0, 2.5) — max error 0.05 bp
const SEG4_A: u64 = 489_044_397;
const SEG4_B: u64 = 520_208_509;
const SEG4_C: u64 = 180_968_122;
const SEG4_C_NEG: bool = true;
const SEG4_D: u64 = 21_457_627;
const SEG4_D_NEG: bool = false;

// Segment 5: [2.5, 3.0) — max error 0.04 bp
const SEG5_A: u64 = 666_513_725;
const SEG5_B: u64 = 307_077_957;
const SEG5_C: u64 = 95_525_141;
const SEG5_C_NEG: bool = true;
const SEG5_D: u64 = 10_023_286;
const SEG5_D_NEG: bool = false;

// Segment 6: [3.0, 3.5) — max error 0.02 bp
const SEG6_A: u64 = 843_404_540;
const SEG6_B: u64 = 128_772_984;
const SEG6_C: u64 = 35_555_970;
const SEG6_C_NEG: bool = true;
const SEG6_D: u64 = 3_293_714;
const SEG6_D_NEG: bool = false;

// Segment 7: [3.5, 4.0) — max error 0.005 bp
const SEG7_A: u64 = 946_950_446;
const SEG7_B: u64 = 39_023_873;
const SEG7_C: u64 = 9_608_306;
const SEG7_C_NEG: bool = true;
const SEG7_D: u64 = 791_489;
const SEG7_D_NEG: bool = false;

/// Standard normal CDF using piecewise cubic polynomials.
/// 8 segments on [0, 4], cubic polynomial per segment.
/// ~15 bytecode instructions vs ~70 for A&S.
public fun normal_cdf(x: u64, x_negative: bool): u64 {
    // Tail clamp: beyond 4σ
    if (x >= 4 * FLOAT_SCALING) {
        return if (x_negative) { 0 } else { FLOAT_SCALING }
    };

    // Precompute x² and x³
    let x2 = math_utils::mul(x, x);
    let x3 = math_utils::mul(x2, x);

    // Select segment and evaluate cubic
    let result = if (x < HALF) {
        // [0.0, 0.5)
        eval_cubic_seg0(x, x2, x3)
    } else if (x < 1 * FLOAT_SCALING) {
        // [0.5, 1.0)
        eval_cubic_seg1(x, x2, x3)
    } else if (x < FLOAT_SCALING + HALF) {
        // [1.0, 1.5)
        eval_cubic_seg2(x, x2, x3)
    } else if (x < 2 * FLOAT_SCALING) {
        // [1.5, 2.0)
        eval_cubic_seg3(x, x2, x3)
    } else if (x < 2 * FLOAT_SCALING + HALF) {
        // [2.0, 2.5)
        eval_cubic_seg4(x, x2, x3)
    } else if (x < 3 * FLOAT_SCALING) {
        // [2.5, 3.0)
        eval_cubic_seg5(x, x2, x3)
    } else if (x < 3 * FLOAT_SCALING + HALF) {
        // [3.0, 3.5)
        eval_cubic_seg6(x, x2, x3)
    } else {
        // [3.5, 4.0)
        eval_cubic_seg7(x, x2, x3)
    };

    // Symmetry: Phi(-x) = 1 - Phi(x)
    if (x_negative) { FLOAT_SCALING - result } else { result }
}

// === Segment evaluators ===
// Each computes: A + B*x + C*x² + D*x³ with precomputed x², x³
// The signs of C and D vary per segment.

fun eval_cubic_seg0(x: u64, x2: u64, x3: u64): u64 {
    let pos = SEG0_A + math_utils::mul(SEG0_B, x);
    let neg = math_utils::mul(SEG0_C, x2) + math_utils::mul(SEG0_D, x3);
    if (pos > neg) { pos - neg } else { 0 }
}

fun eval_cubic_seg1(x: u64, x2: u64, x3: u64): u64 {
    let pos = SEG1_A + math_utils::mul(SEG1_B, x);
    let neg = math_utils::mul(SEG1_C, x2) + math_utils::mul(SEG1_D, x3);
    if (pos > neg) { pos - neg } else { 0 }
}

fun eval_cubic_seg2(x: u64, x2: u64, x3: u64): u64 {
    // C negative, D positive
    let pos = SEG2_A + math_utils::mul(SEG2_B, x) + math_utils::mul(SEG2_D, x3);
    let neg = math_utils::mul(SEG2_C, x2);
    if (pos > neg) { pos - neg } else { 0 }
}

fun eval_cubic_seg3(x: u64, x2: u64, x3: u64): u64 {
    // C negative, D positive
    let pos = SEG3_A + math_utils::mul(SEG3_B, x) + math_utils::mul(SEG3_D, x3);
    let neg = math_utils::mul(SEG3_C, x2);
    if (pos > neg) { pos - neg } else { 0 }
}

fun eval_cubic_seg4(x: u64, x2: u64, x3: u64): u64 {
    // C negative, D positive
    let pos = SEG4_A + math_utils::mul(SEG4_B, x) + math_utils::mul(SEG4_D, x3);
    let neg = math_utils::mul(SEG4_C, x2);
    if (pos > neg) { pos - neg } else { 0 }
}

fun eval_cubic_seg5(x: u64, x2: u64, x3: u64): u64 {
    // C negative, D positive
    let pos = SEG5_A + math_utils::mul(SEG5_B, x) + math_utils::mul(SEG5_D, x3);
    let neg = math_utils::mul(SEG5_C, x2);
    if (pos > neg) { pos - neg } else { 0 }
}

fun eval_cubic_seg6(x: u64, x2: u64, x3: u64): u64 {
    // C negative, D positive
    let pos = SEG6_A + math_utils::mul(SEG6_B, x) + math_utils::mul(SEG6_D, x3);
    let neg = math_utils::mul(SEG6_C, x2);
    if (pos > neg) { pos - neg } else { 0 }
}

fun eval_cubic_seg7(x: u64, x2: u64, x3: u64): u64 {
    // C negative, D positive
    let pos = SEG7_A + math_utils::mul(SEG7_B, x) + math_utils::mul(SEG7_D, x3);
    let neg = math_utils::mul(SEG7_C, x2);
    if (pos > neg) { pos - neg } else { 0 }
}

// === Tests ===

#[test]
fun test_cdf_at_zero() {
    let result = normal_cdf(0, false);
    let diff = if (result > 500_000_000) { result - 500_000_000 } else { 500_000_000 - result };
    assert!(diff < 100, 0); // Should be ~exact
}

#[test]
fun test_cdf_at_one() {
    let result = normal_cdf(1_000_000_000, false);
    let expected = 841_344_746;
    let diff = if (result > expected) { result - expected } else { expected - result };
    assert!(diff < 100_000, 1); // < 0.0001 = 1bp
}

#[test]
fun test_cdf_at_two() {
    let result = normal_cdf(2_000_000_000, false);
    let expected = 977_249_868;
    let diff = if (result > expected) { result - expected } else { expected - result };
    assert!(diff < 100_000, 2); // < 1bp
}

#[test]
fun test_cdf_symmetry() {
    let pos = normal_cdf(1_000_000_000, false);
    let neg = normal_cdf(1_000_000_000, true);
    let sum = pos + neg;
    let diff = if (sum > FLOAT_SCALING) { sum - FLOAT_SCALING } else { FLOAT_SCALING - sum };
    assert!(diff < 100, 3);
}

#[test]
fun test_cdf_tail() {
    assert!(normal_cdf(5_000_000_000, false) == FLOAT_SCALING);
    assert!(normal_cdf(5_000_000_000, true) == 0);
}

#[test]
fun test_cdf_at_half() {
    let result = normal_cdf(500_000_000, false);
    let expected = 691_462_461;
    let diff = if (result > expected) { result - expected } else { expected - result };
    assert!(diff < 100_000, 0); // < 1bp
}

#[test]
fun test_cdf_monotonic() {
    // CDF must be monotonically increasing
    let v0 = normal_cdf(0, false);
    let v1 = normal_cdf(250_000_000, false);  // 0.25
    let v2 = normal_cdf(500_000_000, false);  // 0.5
    let v3 = normal_cdf(1_000_000_000, false); // 1.0
    let v4 = normal_cdf(2_000_000_000, false); // 2.0
    let v5 = normal_cdf(3_000_000_000, false); // 3.0
    assert!(v1 > v0);
    assert!(v2 > v1);
    assert!(v3 > v2);
    assert!(v4 > v3);
    assert!(v5 > v4);
}
